apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consumer-atualizar-contatos-persistent-volume-claim
  labels:
    app: consumer-atualizar-contatos
    tier: backend
  annotations:
    description: "Claim para acessar o volume persistente do microsserviço consumer-atualizar-contatos"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
